In [1]:
import tensorflow as tf
import numpy as np

## 1.默认图与图的构造

In [49]:
a = tf.constant([1,2],name='a',dtype='float32')
b = tf.Variable([2.0,3.0],name='b')
result1 = tf.add_n([a , b],name="add1")#add_n 把一个列表的东西都依次加起来
result2 = tf.add(a , b)
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(result1),sess.run(result2))

[3. 5.] [3. 5.]


In [41]:
print(a.graph)
print(tf.get_default_graph())

In [4]:
v = tf.get_variable("v",shape=[2],initializer=tf.ones_initializer)
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v",shape=[1],initializer=tf.ones_initializer)

print(v.graph)
tf.get_default_graph()

In [5]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("",reuse=True):  #https://blog.csdn.net/IB_H20/article/details/72936574
        print(sess.run(tf.get_variable("v")))

[1. 1.]


In [6]:
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("",reuse=True):
        print(sess.run(tf.get_variable("v")))

[1.]


## 2.try 拼接placeholder

In [8]:
#tf.where tf.greater
data1 = np.array([[1,2,3],
                  [2,3,4],
                  [3,4,5],
                  [4,5,6]])
data2 = np.array([[2,2,2],
                  [3,3,3],
                  [4,4,4],
                  [5,5,5]])

batchsize = 2
features = 3

input1 = tf.placeholder(tf.float32,shape=(batchsize,features),name='input1')
input2 = tf.placeholder(tf.float32,shape=(batchsize,features),name='input2')

#操作
data_add = tf.add(input1,input2)
data_mean = tf.reduce_mean(data_add,reduction_indices=1)
data_mean_re = tf.reshape(data_mean,[batchsize,1]) 
data_mean_f = tf.div(data_mean_re,2)
#data_mean_f = tf.concat(1, [data_mean, data_mean,data_mean])

data_chose = tf.greater(input1,data_mean_f)
data_final = tf.where(data_chose,input1,input2)
#基本test
output = data_final*2

fd_shape = input1.get_shape()
with tf.Session() as sess:
    for i in range(2):
        print(sess.run(output,
                       feed_dict={input1:data1[i*batchsize:(i+1)*batchsize,:],
                                  input2:data2[i*batchsize:(i+1)*batchsize,:]}))

[[4. 4. 6.]
 [6. 6. 8.]]
[[ 8.  8. 10.]
 [10. 10. 12.]]


## 3.tensorboard的使用

In [63]:
tf.reset_default_graph()

In [3]:

writer = tf.summary.FileWriter("/Users/fire/A",tf.get_default_graph())
writer
writer.close()
print('done')
# 然后命令后运行:tensorboard --logdir=/Users/fire/A   =>http://localhost:6006/

done
